POST http://localhost:8080/api/v1/students
Content-Type: application/json
X-Api-Key: SECRET

{
  "name":"Sammi",
  "email":"sammidev10@yahoo.com",
  "gender":"MALE",
  "address":
     {
       "city":"Padang",
       "postCode":"2131",
       "country":"Indonesia"
     },
  "favouriteSubjects":["Computer Science"],
  "totalSpentInBooks":"2000000",
  "created": "2021-06-02T14:15:05.668Z"
}